$('.owl-carousel').owlCarousel({
    loop:true,
    margin:7,
    nav:true,
    responsive:{
        0:{
            items:1.4
        },
        600:{
            items:3.5
        },
        1000:{
            items:5.5
        }
    }
})